name: Auto Release and Version Bump

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v5.6
        id: tag_version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main
          default_bump: patch
          tag_prefix: ""

      - name: Build distribution
        run: ./gradlew build shadowJar generateScripts -PappVersion=${{ steps.tag_version.outputs.new_tag }}

      - name: Rename files
        run: mv build/libs/flux-cli-${{ steps.tag_version.outputs.new_tag }}-all.jar build/libs/flux-cli.jar

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          files: |
            build/libs/flux-cli.jar
            build/release-scripts/install.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}