name: Auto Release and Version Bump

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build and test
        run: ./gradlew build

      - name: Test JAR functionality
        run: |
          echo "Testing JAR with basic commands..."
          java -jar build/libs/fluxzero-cli-dev-all.jar version
          java -jar build/libs/fluxzero-cli-dev-all.jar templates list
          echo "JAR functionality test successful!"

  native-build:
    needs: build-and-test
    uses: ./.github/workflows/native-build.yml

  release:
    runs-on: ubuntu-latest
    needs: [build-and-test, native-build]
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v6.2
        id: tag_version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          release_branches: main
          default_bump: patch
          tag_prefix: ""

      - name: Build distribution
        run: ./gradlew build shadowJar generateScripts -PappVersion=${{ steps.tag_version.outputs.new_tag }}

      - name: Rename files
        run: mv build/libs/fluxzero-cli-${{ steps.tag_version.outputs.new_tag }}-all.jar build/libs/fluxzero-cli.jar

      - name: Verify JAR functionality
        run: |
          echo "Testing JAR with 'templates list' command..."
          java -jar build/libs/fluxzero-cli.jar templates list
          if [ $? -ne 0 ]; then
            echo "JAR verification failed!"
            exit 1
          fi
          echo "JAR verification successful!"

      - name: Download native artifacts
        uses: actions/download-artifact@v4
        with:
          path: native-artifacts

      - name: Prepare native executables for release
        run: |
          mkdir -p build/native-releases
          cp native-artifacts/flux-linux-amd64/flux build/native-releases/flux-linux-amd64
          cp native-artifacts/flux-macos-amd64/flux build/native-releases/flux-macos-amd64
          cp native-artifacts/flux-macos-arm64/flux build/native-releases/flux-macos-arm64
          cp native-artifacts/flux-windows-amd64/flux.exe build/native-releases/flux-windows-amd64.exe
          chmod +x build/native-releases/flux-*

      - name: Verify install scripts
        run: |
          echo "Testing install scripts with native binaries..."
          
          # Test bash install script with Linux binary
          echo "Testing bash install script..."
          export TEST_HOME=$(mktemp -d)
          export HOME=$TEST_HOME
          
          # Use Linux native binary for testing
          LINUX_BINARY="$(pwd)/build/native-releases/flux-linux-amd64"
          bash build/release-scripts/install.sh --install-path --binary="$LINUX_BINARY"
          
          # Check if the native binary was installed
          if [ ! -x "$TEST_HOME/.fluxzero/bin/fz" ]; then
            echo "Install script failed to install native binary!"
            exit 1
          fi
          
          # Test the installed CLI
          $TEST_HOME/.fluxzero/bin/fz version
          if [ $? -ne 0 ]; then
            echo "Installed native binary verification failed!"
            exit 1
          fi
          
          # Check if fz was created in /usr/local/bin
          if [ ! -x "/usr/local/bin/fz" ]; then
            echo "Install script failed to create /usr/local/bin/fz!"
            exit 1
          fi
          
          # Test the fz command directly
          fz version
          if [ $? -ne 0 ]; then
            echo "fz command verification failed!"
            exit 1
          fi
          
          # Also test templates list command via fz
          fz templates list
          if [ $? -ne 0 ]; then
            echo "fz templates list command failed!"
            exit 1
          fi
          
          echo "Bash install script verification successful!"
          
          # Test PowerShell install script syntax (we can't fully test on Linux)
          echo "Verifying PowerShell script syntax..."
          if command -v pwsh >/dev/null 2>&1; then
            pwsh -Command "try { . build/release-scripts/install.ps1 -WhatIf } catch { Write-Host 'Syntax Error'; exit 1 }"
            echo "PowerShell script syntax verification successful!"
          else
            echo "PowerShell not available - skipping syntax check"
          fi
          
          echo "Install scripts verification successful!"
          
          # Cleanup
          sudo rm -f /usr/local/bin/fz
          rm -rf $TEST_HOME

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          files: |
            build/libs/fluxzero-cli.jar
            build/release-scripts/install.sh
            build/release-scripts/install.ps1
            build/native-releases/flux-linux-amd64
            build/native-releases/flux-macos-amd64
            build/native-releases/flux-macos-arm64
            build/native-releases/flux-windows-amd64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}